export { default as SignUp } from './signup'
export { default as SignIn } from './signin'
export { default as Profile } from './profile'
export { default as Main } from './main'
export { default as Nav } from './nav'
